### ISSUE TITLE
BUG AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by TkonstAL** [Spaceginner/MagicPrompt-awebui#3]
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 188, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/content/stable-diffusion-webui/modules/scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/MagicPrompt-awebui/scripts/magic_prompt.py", line 99, in run
    self.gpt = aitextgen(model_folder="./models/MagicPrompt/", tokenizer_file="./models/MagicPrompt/tokenizer.json", to_gpu=torch.cuda.is_available())
  File "/usr/local/lib/python3.9/site-packages/aitextgen/aitextgen.py", line 180, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2006, in from_pretrained
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by nulqwy** [comment]
What version of python do you use?

**Comment by huotarih** [comment]
I just got the same error. This works on other machines tho, all with same python 3.10.6...
Weird.
