### ISSUE TITLE
NameError: name 'aitextgen' is not defined

### ISSUE THREAD

**Issue by Syavick** [Spaceginner/MagicPrompt-awebui#4]
Here are details:

```
Error completing request
Arguments: ('task(ealeew5vnxj74b8)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 1, 75, 0.7, False, True, False, True, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\scripts\magic_prompt.py", line 96, in run
    if type(self.gpt) != aitextgen:
NameError: name 'aitextgen' is not defined
```

Tried with aitextgen 0.5.2 & 0.6.0.

**Comment by nulqwy** [comment]
i havent maintained script for a long time now, so maybe module autoinstallation doesnt work anymore, so try running these commands in webui folder:
```
.\venv\Scripts\activate.bat
pip install aitextgen
```

**Comment by Syavick** [comment]
Aitextgen is installed. It can be some incompatibility of aitextgen with version of pytorch_lightning or something else. If you remove autoinstallation of aitextgen:
change this
```
# Try to import aitextgen, if it is not found, download
try:
    from aitextgen import aitextgen
except:
    print("[MagicPrompt script] aitextgen module is not found, downloading...")
    if os.path.exists("./venv"):
        subprocess.call(["./venv/Scripts/python", "-m", "pip", "-q", "--disable-pip-version-check", "--no-input", "install", "aitextgen"])
    else:
        subprocess.call(["python", "-m", "pip", "-q", "--disable-pip-version-check", "--no-input", "install", "aitextgen"])
    print("[MagicPrompt script] aitextgen module is downloaded")
```

to this

`from aitextgen import aitextgen`

new error will appear:

```
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\scripts\magic_prompt.py", line 35, in <module>
    from aitextgen import aitextgen
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\venv\lib\site-packages\aitextgen\__init__.py", line 1, in <module>
    from .aitextgen import aitextgen  # noqa
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\venv\lib\site-packages\aitextgen\aitextgen.py", line 31, in <module>
    from .train import ATGProgressBar, ATGTransformer
  File "D:\Stable-Diffusion\stable-diffusion-webui-master\venv\lib\site-packages\aitextgen\train.py", line 14, in <module>
    from pytorch_lightning.utilities import _TPU_AVAILABLE
ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities' (D:\Stable-Diffusion\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\utilities\__init__.py)
```

Then I searched for this error and found recomendations to install aitextgen 0.5.2 instead of 0.6.0. But it didn't resolve problem. Version of pytorch_lightning is 1.9.4. Probably I should also play with version of pytorch_lightning.

**Comment by LIFETAB** [comment]
@Syavick have you found a solution?

**Comment by LIFETAB** [comment]
### Fix for: `NameError: name 'aitextgen' is not defined`

# Manual fix:

1. Open your A1111 directory in cmd or your terminal of choice
2. Activate the environment:
   > .\venv\Scripts\activate

3. Install aitextgen version 0.5.1
   > pip install aitextgen==0.5.1

4. Restart your A1111 by going into Extensions and pressing "Apply and restart UI" or just close the A1111 terminal and reopen it.

# Semi-manual fix (recommended):

1. Go to your A1111 installation directory
2. Open the `requirements_versions.txt` file in your Editor
3. Add this line at the end: `aitextgen==0.5.1`
4. Completely restart your A1111 terminal.

### Note: Avoid changing the versions of dependencies for A1111 or any other application unless you understand the potential consequences, as it may lead to further issues.

#### If you have any questions or run into issues feel free to ask me. 
##### @Spaceginner feel free to close this issue.

**Comment by MrPinkX** [comment]
@LIFETAB Did all the steps mentioned, now getting "SafetensorError: Error while deserializing header: HeaderTooLarge"
